image: java:8

stages:
  - build
  - deploy

before_script:
  - chmod +x mvnw

build:
  stage: build
  script: ./mvnw package
  artifacts:
    paths:
      - target/demo-0.0.1-SNAPSHOT.jar

production:
  stage: deploy
  script:
    - curl --location "https://github.com/pivotal-cf/pivnet-cli/releases/download/v2.0.1/pivnet-linux-amd64-2.0.1" | tar zx
    - ./cf7 login -u $CF_USERNAME -p $CF_PASSWORD -a api.cf.aws.portepa.com
    - ./cf7 push
  only:
    - master