apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: voting-app
  name: voting-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: voting-app
  type: LoadBalancer
status:
  loadBalancer: {}
